name: EasySlimeChunkLocator
version: 0.3
author: iKeirNez
main: me.iKeirNez.EasySlimeChunkLocator.EasySlimeChunkLocator
permissions:
    easyslimechunklocator.use:
        description: Allows the user to use the plugin
        default: op